[package]
name = "boiler"
version = "0.1.0"
edition = "2021"
description = "TODO"
authors = ["Mateusz Maćkowski <mateusz@mackowski.org>"]
readme = "README.md"
repository = "https://github.com/m4tx/boiler.git"
homepage = "https://github.com/m4tx/boiler"
license = "MIT"
rust-version = "1.73.0"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.13", features = ["derive"] }
comrak = "0.20.0"
gix = { version = "0.57.1", features = ["basic"] }
markdown = "1.0.0-alpha.16"
once_cell = "1.19.0"
regex = "1.10.2"
serde = { version = "1.0.195", features = ["derive"] }
serde_yaml = "0.9.30"
tera = "1.19.1"
toml = "0.8.8"

[dev-dependencies]
